# Generated by Django 6.1 on 2026-08-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('idiom', 'Idiom'), ('phrasal_verb', 'Phrasal verb'), ('vocabulary', 'Vocabulary')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('meaning', models.TextField()),
                ('ipa', models.CharField(blank=True, max_length=200)),
                ('formality', models.CharField(blank=True, max_length=200)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('collocations', models.JSONField(blank=True, default=list)),
                ('mistake_wrong', models.TextField(blank=True)),
                ('mistake_right', models.JSONField(blank=True, default=list)),
                ('mistake_note', models.TextField(blank=True)),
                ('five_word_meaning', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Review')], default='new', max_length=10)),
            ],
            options={
                'ordering': ['lesson', 'kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('mode', models.CharField(default='Lite', max_length=50)),
                ('focus_theme', models.TextField()),
                ('dialogue_topic', models.CharField(max_length=200)),
                ('difficulty', models.CharField(blank=True, max_length=100)),
                ('lesson_focus', models.TextField(blank=True)),
                ('review_items', models.TextField(blank=True)),
                ('avoiding_repeats', models.TextField(blank=True)),
                ('speaking_practice', models.TextField(blank=True)),
                ('output_correction', models.TextField(blank=True)),
                ('tomorrow_preview', models.TextField(blank=True)),
                ('source_filename', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='BusinessEnglish.expression')),
            ],
            options={
                'ordering': ['expression', 'order'],
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='BusinessEnglish.lesson'),
        ),
        migrations.CreateModel(
            name='UpgradePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('original', models.TextField()),
                ('improved', models.TextField()),
                ('reason', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='BusinessEnglish.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together={('lesson', 'kind', 'order')},
        ),
    ]
