# Generated by Django 6.1.1 on 2026-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, unique=True)),
                ('org', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=256, unique=True)),
                ('qcusername', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('qcquid', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('inactive_status_reason', models.CharField(choices=[('account-currently-active', 'Account currently active'), ('no-entitled-projects', 'No entitled projects'), ('lost-training-not-completedLOST training not completed', 'Lost training not completed'), ('employment terminated', 'Employment terminated')], default='account-currently-active', max_length=256)),
            ],
            options={
                'verbose_name': 'CLO User',
                'verbose_name_plural': 'CLO Users',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=256, unique=True)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
