# Generated by Django 6.1 on 2026-08-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_on', 'id'],
                'indexes': [models.Index(fields=['created_on'], name='tasks_task_created_77703a_idx')],
            },
        ),
    ]
